#!/bin/bash

RUNMODE_AUTHOR="author"
RUNMODE_PUBLISH="publish"
RUNMODE_LOCAL="local"
RUNMODE_DEV="development"
RUNMODE_PROD="prod"
RUNMODE_SAMPLE_CONTENT="samplecontent"
RUNMODE_NO_SAMPLE_CONTENT="nosamplecontent"

RUNMODE_STANDARD_LOCAL="$RUNMODE_LOCAL,$RUNMODE_DEV"
